import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ToasterProvier } from "@/components/Toaster";
import Header from "@/components/header";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["cyrillic"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} antialiased  m-0 min-h-screen flex flex-col`}
      >
        <Header />
        <main className="flex grow">
          {children}
        </main>
        <ToasterProvier />
      </body>
    </html>
  );
}
